<a href="https://colab.research.google.com/github/devidrees/PW-Data-Analytics-July-2026/blob/main/class_5_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Pandas

- numpy is used for computation calculation, because numpy has ndarrays
-
- Pandas is used for data handling because pandas has
  - DATAFRAMES - 2D objects like TABLES
  - SERIES - 1D
- Pandas name has evolved from - PANEL DATA
  - tables used to be called panel data back in the day

pip install pandas
- this command is used to install librareis in python

In [ ]:
import pandas as pd

In [ ]:
# 1D object - with indexes
age = pd.Series([25,30,45,34,28], name = 'Age')
print(age)

age.values # gives an array of values in age
age.index = ['idrees','priyank', 'himanshi','aditya', 'shree'] # gives a range object OR an array of values in index # = ['idrees','priyank', 'himanshi','aditya', 'shree']
age

0    25
1    30
2    45
3    34
4    28
Name: Age, dtype: int64

idrees      25
priyank     30
himanshi    45
aditya      34
shree       28
Name: Age, dtype: int64

In [ ]:
# creating dataframes
# you can create a list of dictionaries - dictionary or dictionaries - dictionary of lists
data = {
    'Name': ['idrees', 'priyank'],
    'Age': [25,27],
    'Salary': [24000,28000]
}


# dataframe
df = pd.DataFrame(data)
df

      Name  Age  Salary
0   idrees   25   24000
1  priyank   27   28000

In [ ]:
# We can import datasets -

# google colab default files
df = pd.read_csv('/content/sample_data/california_housing_test.csv')

# uploaded a csv file here

# paste the path of your data here
titanic_df = pd.read_csv('/content/drive/MyDrive/titanic.csv')

In [ ]:
type(titanic_df)

pandas.core.frame.DataFrame

### Methods to look into data
- or analyse data

In [ ]:
titanic_df.head(2) # default top 5
titanic_df.tail()
titanic_df.sample(3)

titanic_df.info() # returns information about df like

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    object
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    object
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), float64(2), int64(4), object(7)
memory usage: 92.4+ KB

In [ ]:
titanic_df.describe() # statistical values

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [ ]:
titanic_df.shape

titanic_df.dtypes # type of each column
# Object type data when you have text data or combinations of multiple types
# dtypes - check at home

titanic_df.nunique() # how many unique values in each column

survived         2
pclass           3
sex              2
age             88
sibsp            7
parch            7
fare           248
embarked         3
class            3
who              3
adult_male       2
deck             7
embark_town      3
alive            2
alone            2
dtype: int64

In [ ]:
# learn about Indexing with .loc and .iloc

# accessing columns:
# if you access a column in a dataframe, that column is treated as a series object
type(titanic_df['survived'])
#titanic_df.survived
# survived	pclass	sex	age

titanic_df[['survived',	'pclass',	'sex','age']].head()

#df_new  = titanic_df[['survived',	'pclass',	'sex','age']]

   survived  pclass     sex   age
0         0       3    male  22.0
1         1       1  female  38.0
2         1       3  female  26.0
3         1       1  female  35.0
4         0       3    male  35.0

#### 1. .loc - Location by label
- we use labels to target
- [row label, column label]

#### 2. .iloc - integer location
- we use integers to locate things
- [row number, column number]
- you can use slicing etc as well

In [ ]:
titanic_df.loc[2] # a row label
titanic_df.loc[2, 'age'] # row label, column label

titanic_df.loc[[0,1,2,3], ['survived',	'pclass',	'sex','age']]
titanic_df.loc[0:4, ['survived',	'pclass',	'sex','age']]

   survived  pclass     sex   age
0         0       3    male  22.0
1         1       1  female  38.0
2         1       3  female  26.0
3         1       1  female  35.0
4         0       3    male  35.0

In [ ]:
titanic_df.iloc[2] # a row number
titanic_df.iloc[2, 3] # row label, column label

titanic_df.iloc[:6,:4] # row slice, column slice

   survived  pclass     sex   age
0         0       3    male  22.0
1         1       1  female  38.0
2         1       3  female  26.0
3         1       1  female  35.0
4         0       3    male  35.0
5         0       3    male   NaN

In [ ]:
new_df = titanic_df.iloc[:6,:4].copy() #
new_df.index = ['idrees','priyank', 'himanshi','aditya', 'shree','priya']

new_df

          survived  pclass     sex   age
idrees           0       3    male  22.0
priyank          1       1  female  38.0
himanshi         1       3  female  26.0
aditya           1       1  female  35.0
shree            0       3    male  35.0
priya            0       3    male   NaN

In [ ]:
new_df.iloc[0:3, 0:3]

new_df.loc[['idrees','priya'],['pclass','age']]

        pclass   age
idrees       3  22.0
priya        3   NaN

## Grouping and Aggregation
-

In [ ]:
import pandas as pd

data = {
    "Department": ["Sales", "Sales", "IT", "IT", "HR", "HR", "Sales"],
    "City": [
        "New York",
        "Chicago",
        "New York",
        "Chicago",
        "New York",
        "Chicago",
        "New York",
    ],
    "Salary": [70000, 65000, 95000, 88000, 60000, 58000, 72000],
    "Bonus": [5000, 4500, 10000, 7000, 3000, 2500, 6000],
    "Experience": [3, 2, 6, 5, 4, 2, 4],
}

df = pd.DataFrame(data)

In [ ]:
# Aggregation in pandas

df.groupby(["Department"])["Salary"].sum()
df.groupby(["Department"])["Salary"].mean()


df.groupby(["Department"])["Salary"].agg(["mean","sum","min","count"])

df.groupby(["Department","City"])["Salary"].sum().sort_values(ascending= True)

Department  City
HR          Chicago      58000
            New York     60000
Sales       Chicago      65000
IT          Chicago      88000
            New York     95000
Sales       New York    142000
Name: Salary, dtype: int64

## Merge and Concat
- Homework: Merge two dataframes in pandas
- Methods to JOIN two dataframes
-